version : '3.5'

services:
        database:
                image: mysql
                container_name: mysqlDatabase
                hostname: mysql-database
                networks:
                        service-discovery-network:
                                aliases:
                                        - database
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: vehicles
                volumes:
                        - mysqldatabase:/var/lib/mysql
        zuul-gateway-api:
                build: ./zuul-api-gateway
                image: zuul-gateway-img
                container_name: zuulControler
                hostname: zuul-gateway
                networks:
                        service-discovery-network:
                                aliases:
                                        - zuul-gateway
                ports:
                        - 8079:8079
                volumes:
                        - $HOME/.m2:/root/.m2

        login-service:
                build: ./login-service
                image: login-service-img
                container_name: loginContainer
                hostname: login-service
                environment:
                        DATABASE_PASSWORD: password
                        DATABASE_DOMAIN: database
                        DATABASE_SCHEME: authentication
                networks:
                        service-discovery-network:
                                aliases:
                                        - login-service
                volumes:
                        - $HOME/.m2:/root/.m2
                depends_on:
                        - database

        admin-service:
                build: ./admin-service
                image: admin-service-img
                container_name: adminServiceContainer
                hostname:
                        admin-service
                environment:
                        DATABASE_PASSWORD: password
                        DATABASE_DOMAIN: database
                        DATABASE_SCHEME: admindb
                networks:
                        service-discovery-network:
                                 aliases:
                                         - admin-service
                volumes:
                        - $HOME/.m2:/root/.m2
       
        messaging-service:
                 build: ./messaging-service
                 image: messaging-service-img
                 container_name: messagingServiceContainer
                 hostname: messaging-service
                 networks:
                         service-discovery-network:
                                 aliases:
                                         - messaging-service
                 volumes:
                        - $HOME/.m2:/root/.m2
 
        gps-service:
                 build: ./gps-service
                 image: gps-service-img
                 container_name: gpsServiceContainer
                 hostname: gps-service
                 networks:
                         service-discovery-network:
                                 aliases:
                                         - gps-service
                 volumes:
                        - $HOME/.m2:/root/.m2
       
        register-service:
                 build: ./register-service
                 image: register-service-img
                 container_name: registerServiceContainer
                 hostname: register-service
                 networks:
                         service-discovery-network:
                                 aliases:
                                         - register-service
                 volumes:
                        - $HOME/.m2:/root/.m2

        cart-service:
                 build: ./cart-service
                 image: cart-service-img
                 container_name: cartServiceContainer
                 hostname: cart-service
                 environment:
                         DATABASE_PASSWORD: password
                         DATABASE_DOMAIN: database
                         DATABASE_SCHEMA: cartdb
                 networks:
                         service-discovery-network:
                                 aliases:
                                         - cart-service
                 volumes:
                        - $HOME/.m2:/root/.m2
                 depends_on:
                        - database

      
        report-service:
                 build: ./report-service
                 image: report-service-img
                 container_name: reportServiceContainer
                 hostname: report-service
                 networks:
                         service-discovery-network:
                                 aliases:
                                         - report-service
                 volumes:
                        - $HOME/.m2:/root/.m2

        request-service:
                 build: ./request-service
                 image: request-service-img
                 container_name: requestServiceContainer
                 hostname: request-service
                 networks:
                         service-discovery-network:
                                 aliases:
                                         - request-service
                 volumes:
                        - $HOME/.m2:/root/.m2

        search-service:
                 build: ./search-service
                 image: search-service-img
                 container_name: searchServiceContainer
                 hostname: search-service
                 networks:
                         service-discovery-network:
                                 aliases:
                                         - search-service
                 volumes:
                        - $HOME/.m2:/root/.m2

        vehicle-service:
                 build: ./vehicle-service
                 image: vehicle-service-img
                 container_name: vehicleServiceContainer
                 hostname: vehicle-service
                 environment:
                         DATABASE_PASSWORD: password
                         DATABASE_DOMAIN: database
                         DATABASE_SCHEMA: vehicles
                 networks:
                         service-discovery-network:
                                 aliases:
                                         - vehicle-service
                 volumes:
                        - $HOME/.m2:/root/.m2
                 depends_on:
                         - database

networks:
        service-discovery-network:
                name: service-discovery-network
                driver: bridge

volumes:
        mysqldatabase:
